Front/#10/maquetado userpage
MyUDC/FRONT_MyUDC pull request #12
Opened 2024-06-09 23:26 UTC by LUISPINTO90

## ¿Qué se hizo?
- Se instaló font awesome para usar iconos
- en "src/app/user/page.tsx" creó la vista de user
- en "src/app/page.tsx", se cambió el uso de Link por los componentes Button
- en "src/app/sign-up/profile-type/page.tsx" se componetizó el ProfileButton
- en "src/app/welcome/page.tsx" se cambió el uso de Link por los componentes Button
- se simplificó la sintaxis del componente Button para hacerla más legible.

2024-06-10 02:13 UTC, Branyoe commented
Agregas una captura de la vista xfa

2024-06-10 04:46 UTC, LUISPINTO90 commented
![image](https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/80332a32-abd3-4eb0-9ac7-8294169adaa5)

2024-06-10 04:58 UTC, LUISPINTO90 commented
![image](https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/961ff5da-ab10-43ea-8334-f1babd5afab1)

2024-06-10 19:33 UTC, Branyoe requested changes

2024-06-10 19:33 UTC, Branyoe commented on src/app/sign-up/profile-type/page.tsx
> +}
Mover este componente a una carpeta con path /src/components/user

2024-06-10 19:33 UTC, Branyoe commented on src/app/user/page.tsx
> +        </Link>
Hay que hacer nuestras paginas con componentes escalables y reutilizables, la lista de las diferentes opciones que tiene el usuario la puedes componetizar y en ves de cargar los items uno a uno en código plano hacerlo mediante un map

puedesponer el componente en  /src/components/user/...

2024-06-10 19:33 UTC, Branyoe commented on src/components/buttons/Button.tsx
> +  }
Buen aporte, te recomiendo estudies la notación de los corchetes con objetos, sustituye al switch case y es mas legible.

2024-06-11 06:53 UTC, LUISPINTO90 commented on src/app/sign-up/profile-type/page.tsx
> +}
Ya quedó

2024-06-11 07:43 UTC, LUISPINTO90 commented on src/app/user/page.tsx
> +        </Link>
Ya quedó

2024-06-11 07:58 UTC, LUISPINTO90 commented on src/components/buttons/Button.tsx
> +  }
Ya quedó viejillo

2024-06-11 20:16 UTC, Branyoe approved these changes

2024-06-11 20:16 UTC, merged